### PR TITLE
updating dependency constraints for compatibility with 'witherable'

### PR DESCRIPTION
**Pull request by misterbeebee**
Updated dependency versions to get `reflex-0.6.2.3` fixes for  compatibility with `witherable-0.3.2`: https://github.com/reflex-frp/reflex/issues/350)

This forced an adjustment to `dependent-sum` as well, but based on the version number (3rd digit) I expect it's safe.

### CODE REVIEW

**Comment by misterbeebee** [comment]
Don't merge this yet -- I'm still rebuilding CodeWorld. But the build gets a lot farther so far with this change.

**Comment by cdsmith** [comment]
Is this okay to merge now?

**Comment by misterbeebee** [comment]
I couldn't finish building codeworld due to other problems relating to
ghc-lib-parser package's Platform and ToolSetting modules versioning that I
was unable to fix. (WIP my fork at github.com/misterbeebee/codeworld)

So this PR seems to be a net improvement, but I got cold feet because I
don't know why my environment is still broken -- codeworld seems to require
on ghc-lib-platform upper bound  0.20190603
which is over 3 releases and two months old already, and I still couldn't
get my dependencies configured to comply a build, which seemed implausible
to me so I assumed I misconfigured my environment somehow.

**Comment by cdsmith** [comment]
0.20190603 is what is being used on the production server, so that much is correct.  Can you provide the rest of the output and I'll take a look?

**Comment by cdsmith** [comment]
(Maybe open another issue, since this one is closed now)

**Comment by misterbeebee** [comment]
I'm new to GitHub PRs.

Looks like you merged everything on misterbee/codeworld, which included the two commit after I started the PR (constraint `ghc-lib-parser <= 0.20190603`)

With these changes, I was able to finish building and running codeworld.
I had to run `cabal_install ghc-lib-parser-0.20190603` in my local shell environment in order to make it available to the codeworld build.

So, 
(1) my dev machine works for now :-)
(2) It seems that `ghc-lib-parser-0.20190603` isn't being set up hermetically/repeatably. But I don't know enough about cabal to say what's the proper way to make it so.
Maybe `ghc-lib-parser-0.20190603` needs to be added to the list of packages at build.sh:46  (where ./codeworld-compiler is named) ?

Probably better to upgrade `codeworld-compiler` to use the latest `ghc-lib-parser` API.
I've filed an issue for that: 
https://github.com/google/codeworld/issues/1100

**Comment by cdsmith** [comment]
That's strange.  Once the cabal bounds were changed, cabal should definitely have downloaded and installed the appropriate version of ghc-lib-parser on its own.  If this comes up again, I'll look into it, but since the state of the dependencies has changed anyway, it's hard to go back and figure out what happened now.

**Pull request merged**
