### PR TITLE
Travis-CI build stages

### PR DESCRIPTION
**Pull request by peterbecich**
This should solve the problem of build time-outs.  Not sure if this will pass, yet: https://travis-ci.org/peterbecich/codeworld/builds/604293274

### CODE REVIEW

**Comment by cdsmith** [comment]
Well, Travis passes on this pull request, which is more than I can say for HEAD.  I'm in favor.

**Comment by cdsmith** [comment]
I notice you still have WIP in the title.  Let me know when you are ready to merge.

**Comment by peterbecich** [comment]
please merge

**Comment by cdsmith** [comment]
Done

**Pull request merged**
