### PR TITLE
Here's a strawman PR changing the highlighting behaviour.

### PR DESCRIPTION
**Pull request by tgdavies**
This is still triggered by having the cursor next to a parenthesis -- perhaps it should also trigger when the cursor is in a function name.

### CODE REVIEW

**Comment by tgdavies** [comment]
I've signed the CLA

**Comment by cdsmith** [comment]
It doesn't look like I can find a CLA for you.  Did you sign it with this github username?

**Comment by tgdavies** [comment]
Oops -- I thought I'd used my email address as my github user name -- should be fixed now.

**Comment by tgdavies** [comment]
I had git configured with my work email -- I'll close this PR and and re-fork so I can use the correct email address.

**Comment by cdsmith** [comment]
Okay, sounds good.

I tried this out on a test server, and noticed that the bounds for the highlight seem to be off by one at the beginning of a line when defining a function.

**Pull request closed without merging**
